ARG BASE_IMAGE=avisactl-base
FROM ${BASE_IMAGE}

WORKDIR /project

# Opcional: mejora la cache con crates
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

# Luego sí copia el resto del código
COPY . .

# No compiles aquí. Solo deja todo listo.
